---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.es.name }}
  {{- if .Values.services.es.annotations }}
  annotations:
    {{- range .Values.services.es.annotations }}
    {{ .key }}: "{{ .value }}"
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  ports:
  - port: {{ .Values.services.es.port }}
    name: {{ .Values.services.es.port_name }}
{{- if .Values.services.es.public }}
  type: {{ .Values.services.es.type }}
{{- else }}
  clusterIP: None
{{- end }}
  selector:
    name: {{ .Values.services.discovery.app_selector }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.discovery.service_name}}
  labels:
    app: {{ .Values.cluster_name }}
    name: {{ .Values.master_name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  ports:
  - port: {{ .Values.services.discovery.cluster_port }}
    name: {{ .Values.services.discovery.cluster_port_name }}
    protocol: TCP
  clusterIP: None
  selector:
    app: {{.Values.name}}

---
{{- if .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.services.es.name }}
          servicePort: {{ .Values.services.es.port }}

{{- end }}
